import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import setList from "../data/set-list.json";
import Link from "next/link";
import Layout from "@/components/layout";
import Button from "@/components/button";
import styled from "styled-components";

const HomeContainer = styled.div`
  width: 400px;
  margin: 40px auto;

  & .image-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 20px;
  }
`;

const LinksWrapper = styled.div`
  textalign: center;
  display: grid;

  & button {
    margin-bottom: 20px;
    margin-right: 10px;
  }
`;

function Home() {
  return (
    <>
      <Head>
        <title>Orange Pill in a Pack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeContainer>
          <div className="image-row">
            {/* <Image
              src="/images/logos/mtg-logo-orange.webp"
              height={112}
              width={250}
            />
            <Image
              src="/images/logos/alpha-a-logo.png"
              height={75}
              width={75}
            /> */}
          </div>
          <LinksWrapper>
            <Link href="/cards">
              <Button href="/cards">Card Images</Button>
            </Link>
            <Link href="/cards">
              <Button>Card List</Button>
            </Link>
            <Link href="/random-pack">
              <Button>Open a Booster Pack</Button>
            </Link>
            <Link href="/cards">
              <Button>About Series 1</Button>
            </Link>
            <Link href="/cards">
              <Button>About Series 2</Button>
            </Link>
            <Link href="/cards">
              <Button>Secondary Market</Button>
            </Link>
            <Link href="https://btc-tc.com/" target="_blank">
              <Button>Buy Bitcoin Trading Cards</Button>
            </Link>
          </LinksWrapper>
        </HomeContainer>
      </Layout>
    </>
  );
}

export default Home;
